import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import {getFirestore,collection,getDocs,query,orderBy} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
const $=id=>document.getElementById(id),config=window.ETR_FIREBASE_CONFIG||{},admins=(window.ETR_ADMIN_EMAILS||[]).map(x=>x.toLowerCase());let rows=[];
if(!config.apiKey||config.apiKey==='REPLACE_ME')$('adminMessage').textContent='Firebase is not configured. See README.md.';
const app=initializeApp(config),auth=getAuth(app),db=getFirestore(app);
function date(v){const d=v?.toDate?v.toDate():v?new Date(v):null;return d&&!isNaN(d)?d.toLocaleString('en-CA'):'—'}
function render(){const completed=rows.filter(r=>(r.quizScore||0)>=80&&r.completed?.length>=31).length,avg=rows.length?Math.round(rows.reduce((s,r)=>s+(r.quizScore||0),0)/rows.length):0;$('totalStat').textContent=rows.length;$('completeStat').textContent=completed;$('progressStat').textContent=rows.length-completed;$('scoreStat').textContent=avg+'%';$('recordsBody').innerHTML=rows.map(r=>`<tr><td>${r.employeeName||'—'}</td><td>${r.email||'—'}</td><td>${r.completed?.length||0}/31</td><td>${r.quizScore||0}%</td><td><span class="status-pill ${(r.quizScore||0)>=80&&r.completed?.length>=31?'complete':'progress'}">${(r.quizScore||0)>=80&&r.completed?.length>=31?'Complete':'In progress'}</span></td><td>${date(r.lastUpdated)}</td><td>${r.certificateId||'—'}</td></tr>`).join('')}
async function load(){const snap=await getDocs(query(collection(db,'trainingUsers'),orderBy('lastUpdated','desc')));rows=snap.docs.map(d=>d.data());render()}
$('adminLoginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('adminEmail').value.trim(),$('adminPassword').value)}catch(e){$('adminMessage').textContent=e.message}};
$('adminSignOut').onclick=()=>signOut(auth);
$('exportBtn').onclick=()=>{const headers=['Employee','Email','Modules Completed','Exam Score','Status','Started','Completed','Last Updated','Certificate ID'];const csv=[headers,...rows.map(r=>[r.employeeName||'',r.email||'',r.completed?.length||0,r.quizScore||0,(r.quizScore||0)>=80&&r.completed?.length>=31?'Complete':'In progress',date(r.startedAt),date(r.completedAt),date(r.lastUpdated),r.certificateId||''])].map(a=>a.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='etr-training-records.csv';a.click()};
onAuthStateChanged(auth,async u=>{if(u&&admins.includes((u.email||'').toLowerCase())){$('adminLogin').hidden=true;$('adminDashboard').hidden=false;await load()}else{$('adminLogin').hidden=false;$('adminDashboard').hidden=true;if(u){$('adminMessage').textContent='This account is not listed as an administrator.';await signOut(auth)}}});
