(()=>{
const data=window.COURSE_DATA,state=ProgressStore.load();let current=0,utter=null,voices=[];const $=id=>document.getElementById(id);
function pct(){return Math.round(state.completed.length/data.length*100)}
function allModulesComplete(){return data.every(m=>state.completed.includes(m.id)&&state.moduleChecks[m.id])}
function updateProgress(){
 const p=pct();$('globalProgress').style.width=p+'%';$('progressText').textContent=`${state.completed.length} of ${data.length} complete`;$('progressRing').style.background=`conic-gradient(#fff ${p}%,rgba(255,255,255,.2) ${p}% 100%)`;$('progressRing').querySelector('span').textContent=p+'%';
 document.querySelectorAll('.nav-item').forEach((b,i)=>{b.classList.toggle('done',state.completed.includes(data[i].id));b.classList.toggle('checked',!!state.moduleChecks[data[i].id])});
 const unlocked=allModulesComplete();$('finalAssessment').classList.toggle('locked',!unlocked);$('submitQuiz').disabled=!unlocked;$('examIntro').textContent=unlocked?'All modules are complete. Score 80% or higher to unlock your completion certificate.':'Complete all module knowledge checks and acknowledgements before taking the final exam.';
 if(state.quizScore>=80&&!$('finalAssessment').hidden)$('certificateSection').hidden=false
}
function nav(){const n=$('moduleNav');n.innerHTML=data.map((m,i)=>`<button class="nav-item ${state.completed.includes(m.id)?'done':''}" data-i="${i}"><span class="nav-index">${state.completed.includes(m.id)?'✓':i+1}</span><span class="nav-label">${m.title}</span></button>`).join('');n.onclick=e=>{const b=e.target.closest('.nav-item');if(b)openModule(+b.dataset.i)}}
function formatPolicy(text){return text.split(/\n\n+/).map(p=>`<p>${escapeHtml(p).replace(/\n/g,'<br>')}</p>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function renderModuleCheck(m){const q=MODULE_CHECKS[m.id];const passed=!!state.moduleChecks[m.id];$('moduleQuestion').innerHTML=`<fieldset class="question module-question"><legend>${escapeHtml(q.q)}</legend>${q.o.map((o,j)=>`<label class="option"><input type="radio" name="moduleQ" value="${j}" ${passed&&j===q.a?'checked':''}> ${escapeHtml(o)}</label>`).join('')}</fieldset>`;$('moduleCheckResult').textContent=passed?'Passed. You may complete this module.':'';$('moduleKnowledge').classList.toggle('passed',passed);$('checkStatus').textContent=passed?'✓ Knowledge check passed':'Knowledge check not yet passed';$('checkStatus').classList.toggle('passed',passed);$('completeBtn').disabled=!passed}
function openModule(i){speechSynthesis.cancel();current=i;const m=data[i];$('welcome').hidden=true;$('finalAssessment').hidden=true;$('certificateSection').hidden=true;$('moduleView').hidden=false;$('moduleCategory').textContent=m.category;$('moduleTitle').textContent=m.title;$('modulePages').textContent=`Handbook pages ${m.start}${m.end>m.start?'–'+m.end:''}`;$('takeawayList').innerHTML=(m.takeaways.length?m.takeaways:['Review the complete policy wording below and apply it to your work.']).map(x=>`<li>${escapeHtml(x)}</li>`).join('');$('policyContent').innerHTML=formatPolicy(m.text);$('policyContent').classList.remove('expanded');$('expandBtn').textContent='Expand all';$('ackCheck').checked=state.completed.includes(m.id);$('prevBtn').disabled=i===0;$('nextBtn').textContent=i===data.length-1?'Go to final exam':'Next policy →';document.querySelectorAll('.nav-item').forEach((b,j)=>b.classList.toggle('active',j===i));renderModuleCheck(m);$('moduleView').scrollIntoView({behavior:'smooth'});$('sidebar').classList.remove('open')}
function submitModuleCheck(){const m=data[current],q=MODULE_CHECKS[m.id],a=document.querySelector('input[name=moduleQ]:checked');if(!a){$('moduleCheckResult').textContent='Choose an answer before submitting.';return}if(+a.value===q.a){state.moduleChecks[m.id]=true;ProgressStore.save(state);$('moduleCheckResult').textContent='Correct. Knowledge check passed.';$('moduleKnowledge').classList.add('passed');$('checkStatus').textContent='✓ Knowledge check passed';$('checkStatus').classList.add('passed');$('completeBtn').disabled=false;updateProgress()}else{$('moduleCheckResult').textContent='Not quite. Review the policy and try again.';$('moduleKnowledge').classList.remove('passed')}}
function complete(){const m=data[current];if(!state.moduleChecks[m.id]){alert('Please pass the knowledge check before completing this module.');return}if(!$('ackCheck').checked){alert('Please confirm that you reviewed and understand this policy.');return}if(!state.completed.includes(m.id))state.completed.push(m.id);ProgressStore.save(state);nav();updateProgress();if(current<data.length-1)openModule(current+1);else{showExam()}}
function loadVoices(){voices=speechSynthesis.getVoices();$('voiceSelect').innerHTML=voices.map((v,i)=>`<option value="${i}">${v.name} (${v.lang})</option>`).join('')}
function speak(){speechSynthesis.cancel();const m=data[current];utter=new SpeechSynthesisUtterance(`${m.title}. Key refresher points. ${m.takeaways.join('. ')}. Full policy content. ${m.text}`);utter.rate=parseFloat($('rateSelect').value);const v=voices[+$('voiceSelect').value];if(v)utter.voice=v;utter.onstart=()=>$('audioStatus').textContent='Reading policy';utter.onend=()=>$('audioStatus').textContent='Finished';utter.onerror=()=>$('audioStatus').textContent='Narration stopped';speechSynthesis.speak(utter)}
function showOverview(){speechSynthesis.cancel();$('moduleView').hidden=true;$('finalAssessment').hidden=true;$('certificateSection').hidden=true;$('welcome').hidden=false;$('welcome').scrollIntoView({behavior:'smooth'})}
function showExam(){speechSynthesis.cancel();$('welcome').hidden=true;$('moduleView').hidden=true;$('finalAssessment').hidden=false;$('certificateSection').hidden=!(state.quizScore>=80);$('finalAssessment').scrollIntoView({behavior:'smooth'})}
$('startBtn').onclick=()=>{const idx=data.findIndex(m=>!state.completed.includes(m.id));openModule(idx<0?0:idx)};$('openExamBtn').onclick=showExam;$('closeModule').onclick=showOverview;$('submitModuleCheck').onclick=submitModuleCheck;$('completeBtn').onclick=complete;$('prevBtn').onclick=()=>openModule(current-1);$('nextBtn').onclick=()=>current<data.length-1?openModule(current+1):showExam();$('expandBtn').onclick=()=>{const p=$('policyContent');p.classList.toggle('expanded');$('expandBtn').textContent=p.classList.contains('expanded')?'Collapse':'Expand all'};$('playBtn').onclick=speak;$('pauseBtn').onclick=()=>{if(speechSynthesis.paused){speechSynthesis.resume();$('audioStatus').textContent='Reading policy'}else{speechSynthesis.pause();$('audioStatus').textContent='Paused'}};$('stopBtn').onclick=()=>{speechSynthesis.cancel();$('audioStatus').textContent='Stopped'};$('themeBtn').onclick=()=>document.body.classList.toggle('dark');$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('searchInput').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.nav-item').forEach((b,i)=>b.hidden=!(data[i].title+' '+data[i].text).toLowerCase().includes(q))};$('resetBtn').onclick=()=>{if(confirm('Reset all course progress, module checks and final exam results?')){ProgressStore.reset();location.reload()}};
renderQuiz();$('submitQuiz').onclick=()=>{if(!allModulesComplete()){ $('quizResult').textContent='Complete every module and knowledge check before taking the final exam.';return}let score=0;QUIZ_QUESTIONS.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q.a)score++});const percent=Math.round(score/QUIZ_QUESTIONS.length*100);state.quizScore=Math.max(state.quizScore||0,percent);ProgressStore.save(state);$('quizResult').textContent=percent>=80?`Passed: ${percent}%. Your certificate is unlocked.`:`Score: ${percent}%. Review the policies and try again. You need 80% to pass.`;updateProgress();if(percent>=80)$('certificateSection').scrollIntoView({behavior:'smooth'})};speechSynthesis.onvoiceschanged=loadVoices;loadVoices();nav();updateProgress();setupCertificate(state)
})();
