window.MODULE_CHECKS={
'important-contacts':{q:'Who should employees contact for immediate operational direction while on duty?',o:['A member of the public','The on-duty Yard Coordinator or appropriate supervisor','A customer','Only the payroll office'],a:1},
'health-safety':{q:'According to ETR’s Health and Safety Policy, who is responsible for safety?',o:['Management only','The safety committee only','Everyone at every level','Outside regulators only'],a:2},
'violence-statement':{q:'What must employees do when they witness or experience workplace violence or harassment?',o:['Ignore it unless injury occurs','Report it through the identified reporting channels','Post it online','Wait until annual training'],a:1},
'federal-violence':{q:'Who is identified as the designated recipient for a harassment or violence notice?',o:['Any co-worker','The HR Manager/designated recipient named in the policy','A customer','Police only'],a:1},
'irs':{q:'What are the three basic worker rights under the Internal Responsibility System?',o:['Know, participate and refuse dangerous work','Inspect, discipline and dismiss','Train, supervise and audit','Stop, look and listen'],a:0},
'work-refusal':{q:'What is the first step when an employee has reasonable cause to refuse dangerous work?',o:['Leave the site without notice','Notify the employer or supervisor and follow the prescribed process','Continue working until the end of shift','Call a customer'],a:1},
'fatigue':{q:'Fatigue management at ETR is best described as:',o:['Only the employee’s responsibility','Only management’s responsibility','A shared responsibility','Only the union’s responsibility'],a:2},
'communications':{q:'When may a communication device be used while operating equipment or driving?',o:['Any time the employee chooses','Only when permitted by law, policy and safe operating conditions','Only for personal calls','Never under any circumstance'],a:1},
'trespassing':{q:'What should an employee do after observing a trespasser?',o:['Approach alone','Report the location and details to a supervisor or another employee','Ignore the person','Post a photo online'],a:1},
'sharps':{q:'How should a found sharp be handled?',o:['With bare hands','Using the approved PPE, tools and sharps container procedure','Placed in regular garbage','Left unreported'],a:1},
'substance':{q:'Employees must report for duty in what condition?',o:['Free from impairment and fit for duty','Only free from alcohol','Able to work despite medication effects','Any condition if the shift is short'],a:0},
'terminal':{q:'What is expected before the end of a regular shift?',o:['Leave work areas as-is','Inspect and clean the assigned work area, equipment or vehicle','Only report overtime','Turn off personal phones'],a:1},
'smoke':{q:'Where do smoke and vape restrictions apply?',o:['Only inside offices','Across the workplace as set out in the policy','Only around customers','Only during daytime'],a:1},
'emergency':{q:'What should employees do when the evacuation signal is sounded?',o:['Finish the current task first','Shut down safely, evacuate and report to the assembly area','Drive home','Wait for an email'],a:1},
'inspection':{q:'Why are workplace inspections and housekeeping important?',o:['To assign blame','To identify and correct hazards before incidents occur','To reduce training','To replace supervision'],a:1},
'first-aid':{q:'What should happen after first aid is provided for a workplace injury?',o:['Nothing further','The incident must be reported and documented as required','The employee must leave immediately','Only payroll is notified'],a:1},
'whmis':{q:'WHMIS training helps workers understand:',o:['Payroll deductions','Hazardous products, labels and safety data sheets','Vacation scheduling','Customer billing'],a:1},
'hazard-assessment':{q:'When should a hazard assessment be reviewed?',o:['Only once when a job is created','When work, equipment, conditions or hazards change','Only after an injury','Every ten years'],a:1},
'boots':{q:'Safety footwear must be:',o:['Any comfortable shoe','Approved, suitable for the hazard and maintained in good condition','Optional for experienced workers','Worn only during inspections'],a:1},
'vests':{q:'High-visibility apparel should be:',o:['Kept clean, visible and in serviceable condition','Covered by dark clothing','Worn only by visitors','Used only at night'],a:0},
'ppe':{q:'How is required PPE selected?',o:['By personal preference','Based on the task, policy and hazard assessment','By seniority','Only by weather'],a:1},
'msd':{q:'What is a key way to prevent musculoskeletal disorders?',o:['Ignore early discomfort','Identify risk factors and use proper ergonomic or lifting controls','Lift faster','Avoid reporting symptoms'],a:1},
'lifting':{q:'Who may operate a lifting device?',o:['Any employee','Only trained, competent and authorized workers','Any visitor with a licence','Customers'],a:1},
'mewp':{q:'Before using a mobile elevated work platform, the operator must:',o:['Rely on memory only','Be trained, authorized and complete required inspections','Ask a visitor to spot','Skip the pre-use check'],a:1},
'forklift':{q:'What is required before operating a forklift?',o:['Only a road driver licence','Training, authorization and a pre-use inspection','Permission from a co-worker','One week of service'],a:1},
'fall':{q:'When is fall protection required?',o:['Only when an employee feels unsafe','When the identified fall hazard and applicable requirements call for it','Only outdoors','Only for contractors'],a:1},
'incident':{q:'What is the primary purpose of an incident investigation?',o:['Assign blame','Identify causes and prevent recurrence','Delay work','Prepare publicity'],a:1},
'confined':{q:'Entry into a confined space requires:',o:['No preparation if entry is brief','Authorization, hazard assessment and all required controls','Only a flashlight','A verbal promise'],a:1},
'driving':{q:'Safe driving requires employees to:',o:['Follow traffic laws, remain attentive and adjust to conditions','Use a phone whenever traffic is slow','Exceed limits to meet schedules','Drive while fatigued if necessary'],a:0},
'hearing':{q:'When must hearing protection be worn?',o:['When noise exposure or posted requirements call for it','Only once a year','Only by new employees','Never'],a:0},
'life-savers':{q:'What is the purpose of ETR’s Life Savers?',o:['Optional suggestions','Critical rules intended to prevent serious injury and fatality','Customer service standards','Payroll reminders'],a:1}
};
